name: Weekly Report Mentor Comment Check

on:
  pull_request:
    branches:
        - main

permissions:
  contents: write

jobs:
  check-mentor-comment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: action/checkout@v2
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v14.6

      - name: List all changed files
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "$file was changed"
          done

      # - name: Check Mentor Comment
      #   run: |
      #       changedFiles=$(git diff --name-only HEAD^)
      #       # Check if the PR contains markdown files
      #       if ! git diff --name-only --diff-filter=AMR --cached | grep -qE '\.md$'; then
      #           echo "PR does not contain markdown files. Assume the PR is not a `Weekly Report`."
      #           exit 0
      #       fi

      #       # Check if the PR contains weekly report files
      #       if git diff --name-only --diff-filter=AMR --cached | xargs grep -qE '### 实习项目.*\n.*### 本周工作'; then
      #           echo "PR contains weekly report files"
      #           # Check if the weekly report files contain mentor review section
      #           if ! git diff --name-only --diff-filter=AMR --cached | xargs grep -qE '### 导师点评.*\n.*[^待填写]'; then
      #               echo "Mentor review section is missing or empty"
      #               exit 1
      #           fi
      #       fi